# Fast-Agent Configuration
# Use the combined MCP + Slack bot server

default_model: openai

models:
  openai:
    provider: openai
    model: gpt-4o
    temperature: 0.7
    max_tokens: 4000

# MCP Server configuration
mcp_servers:
  inflection_prod:
    url: http://inflection-journey-stats-bot-python-production.up.railway.app
    
  inflection:
    url: http://localhost:8000/
#     description: "Inflection.io marketing automation tools (Combined MCP + Slack bot server)" 