[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "git", "curl"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "source venv/bin/activate && python web_server.py" 