[build]
builder = "nixpacks"

[deploy]
startCommand = "source venv/bin/activate && python web_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PIP_USER = "false" 